apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gradio-appid
spec:
  to:
    kind: Service
    name: gradio-appid
  port:
    targetPort: 8000
  tls:
    termination: edge
